### ISSUE TITLE
bot updates

### ISSUE THREAD

**Issue by Leenkss** [oldnapalm/zoffline-bots#1]
how can i update bots data ?

**Comment by oldnapalm** [comment]
Please elaborate your question, it's not clear what you want to achieve.

**Comment by Leenkss** [comment]
can I add my friends' workouts as bots?

**Comment by oldnapalm** [comment]
Only if they do the workouts using zwift-offline with the "ghosts" option enabled, then the ghosts will be saved in their profile directory and will be loaded as bots if you have the file "enable_bots.txt" in the storage directory. If they use another zwift-offline installation you can copy their ghosts directory (for example `storage/1/ghosts`) to your `storage/bots` directory.
